### ISSUE TITLE
Project webpage is down

### ISSUE THREAD

**Issue by mkoncek** [jakartaee/jaf-api#104]
**Describe the bug**
The project webpage as mentioned in the Readme: https://eclipse-ee4j.github.io/jaf/ is not working.

**Comment by pzygielo** [comment]
Try https://jakartaee.github.io/jaf-api/

**Comment by pzygielo** [comment]
Maintainers could update `About` of this repository.

**Comment by lukasj** [comment]
refreshed https://jakartaee.github.io/jaf-api/ as well as https://eclipse-ee4j.github.io/angus-activation/. Let me know should there be any broken/old pointers. Thanks.
